// Auto-generated by tools/gen-bucklespring-attack.py -- DO NOT EDIT.
//
// Short attack samples cut from reference WAV recordings.
// Each entry holds a slice of the first few milliseconds of the real
// recording — the complex multi-burst transient that is hard to synthesize.
// The synthetic tail (in bucklespring.cxx) crossfades in after this window.

module;
#include <array>
#include <cstdint>
#include <span>

export module fs8.mods:bucklespring_attack;

export namespace fs8 {

    /// Offset + length into the attack PCM blob for one (keycode, pressed) pair.
    struct [[nodiscard]] attack_entry {
        uint32_t offset;  ///< byte offset into bucklespring_attack_blob
        uint16_t frames;  ///< number of mono int16 samples
    };

    /// Concatenated int16 PCM attack samples (mono, 44100 Hz, peak-normalized).
    extern uint8_t const bucklespring_attack_blob[];
    extern uint32_t const bucklespring_attack_blob_size;

    /// Lookup table: [keycode][pressed] -> attack_entry.
    /// Missing keys fall back to a nearby measured key's attack.
    extern std::array<std::array<attack_entry, 2>, 256> const bucklespring_attack_table;

    /// Attack sample rate (always 44100; resampled at render time).
    inline constexpr uint32_t attack_sample_rate = 44'100;

} // namespace fs8
