// Auto-generated by tools/gen-bucklespring.py -- DO NOT EDIT.
//
// Per-keycode synthesis voice struct and extern array declarations
// for the bucklespring sound profile. Array definitions are in bucklespring_data.cxx.

module;
#include <array>
#include <cstdint>

export module fs8.mods:bucklespring_data;

export namespace fs8 {

    /// Per-keycode synthesis voice parameters.
    struct bucklespring_voice {
        float primary_freq;       ///< main spring resonance (Hz)
        float primary_q;          ///< primary bandpass Q
        float secondary_freq;     ///< secondary resonance (Hz)
        float secondary_q;        ///< secondary bandpass Q
        float ring_ms;            ///< resonance decay time (ms)
        float peak_dbfs;          ///< target peak amplitude (dBFS)
        float transient_slope;    ///< transient noise slope (dB/oct)
        float ring_slope;         ///< ring noise slope (dB/oct)
    };

    extern const std::array<bucklespring_voice, 256> bucklespring_press_params;
    extern const std::array<bucklespring_voice, 256> bucklespring_release_params;

} // namespace fs8
