// Auto-generated by tools/gen-bucklespring.py -- DO NOT EDIT.
//
// Per-keycode synthesis parameter struct and extern array declarations
// for the bucklespring sound profile. Array definitions are in bucklespring_data.cxx.

module;
#include <array>
#include <cstdint>

export module fs8.mods:bucklespring_data;

export namespace fs8 {

    /// Per-keycode synthesis parameters.
    struct bucklespring_params {
        float primary_freq;       ///< main spring resonance (Hz)
        float primary_q;          ///< primary bandpass Q
        float secondary_freq;     ///< secondary resonance (Hz)
        float secondary_q;        ///< secondary bandpass Q
        float ring_ms;            ///< resonance decay time (ms)
        float peak_dbfs;          ///< target peak amplitude (dBFS)
        float contact_ms;         ///< time of first energy peak — keycap contact (ms)
        float snap_ms;            ///< time of buckle snap — the loud event (ms)
        float snap_bw_ms;         ///< snap burst width (~0.5–1.5 ms)
    };

    extern const std::array<bucklespring_params, 256> bucklespring_press_params;
    extern const std::array<bucklespring_params, 256> bucklespring_release_params;

} // namespace fs8
