// Auto-generated by tools/gen-bucklespring.py -- DO NOT EDIT.
//
// Per-keycode synthesis parameters for the chime sound profile.
// Each voice describes a biquad-bandpass resonator driven by shaped noise.

module;
#include <array>
#include <cstdint>

export module fs8.mods:chime_data;

export namespace fs8 {

    /// Per-keycode synthesis voice parameters.
    struct chime_voice {
        float center_freq;      ///< resonant frequency (Hz)
        float bandwidth;        ///< bandpass width at -10 dB (Hz)
        float q_factor;         ///< filter resonance (center / bandwidth)
        float attack_ms;        ///< linear fade-in time
        float decay_fast_ms;    ///< fast exponential decay (initial snap)
        float decay_slow_ms;    ///< slow exponential decay (resonance tail)
        float decay_fast_mix;   ///< 0 = all slow, 1 = all fast
        float duration_ms;      ///< total audible duration
        float noise_mix;        ///< 0 = pure tonal, 1 = pure noise
        float pitch_drift;      ///< frequency sweep during attack (Hz +/-)
        float gain;             ///< peak amplitude scaling
    };


    extern const std::array<chime_voice, 256> chime_press_params;

    extern const std::array<chime_voice, 256> chime_release_params;

} // namespace fs8
