// Auto-generated by tools/gen-sampled.py -- DO NOT EDIT.
//
// Keystroke samples cut from CC0 reference recordings (no attribution
// required; sources listed in sampled_data.cxx).
//
// To regenerate:
//   python3 tools/gen-sampled.py --ref-dir ~/.cache/foresight-sound-refs-cc0

module;
#include <array>
#include <cstddef>
#include <cstdint>

export module fs8.sound:sampled_data;

export namespace fs8 {

    /// Byte offset + length (mono int16 frames) of one sample in the blob.
    struct [[nodiscard]] sampled_slice {
        uint32_t offset;
        uint16_t frames;
    };

    /// Concatenated int16 PCM samples (mono, 48 kHz, peak-normalized).
    extern uint8_t const  sampled_blob[];
    extern uint32_t const sampled_blob_size;

    /// Slice table; layout documented by the *_count constants below.
    extern std::array<sampled_slice, 8> const sampled_slices;

    /// Sample rate of every embedded slice.
    inline constexpr uint32_t sampled_rate = 48'000;

    inline constexpr std::size_t sampled_total        = 8;
    /// slices[0 .. sampled_normal_count) -- computer-keyboard keystrokes.
    inline constexpr std::size_t sampled_normal_count = 6;
    /// slices[sampled_type_first .. + sampled_type_count) -- typewriter keys.
    inline constexpr std::size_t sampled_type_first   = 6;
    inline constexpr std::size_t sampled_type_count   = 1;
    /// slices[sampled_space_index] -- typewriter spacebar.
    inline constexpr std::size_t sampled_space_index  = 7;

} // namespace fs8
