// Auto-generated by tools/gen-typewriter-attack.py -- DO NOT EDIT.
//
// Short attack samples cut from the CC0 typewriter reference recording.
// Each entry holds the first few milliseconds of a real typebar strike —
// the sharp multi-burst transient that is hard to synthesize.  The
// synthetic tail (in typewriter.cxx) crossfades in after this window.
// Releases use no attack: the key-return tick is pure synthesis.

module;
#include <array>
#include <cstdint>

export module fs8.mods:typewriter_attack;

export namespace fs8 {

    /// Offset + length into the attack PCM blob for one keycode (press only).
    struct [[nodiscard]] typewriter_attack_entry {
        uint32_t offset;  ///< byte offset into typewriter_attack_blob
        uint16_t frames;  ///< number of mono int16 samples
    };

    /// Concatenated int16 PCM attack samples (mono, peak-normalized).
    extern uint8_t const typewriter_attack_blob[];
    extern uint32_t const typewriter_attack_blob_size;

    /// Lookup table: [keycode] -> attack_entry (presses; releases are empty).
    /// Keys cycle round-robin through the isolated reference strikes.
    extern std::array<typewriter_attack_entry, 256> const typewriter_attack_table;

    /// Attack sample rate (resampled at render time if needed).
    inline constexpr uint32_t typewriter_attack_rate = 48'000;

} // namespace fs8
