
#include "common/tests_common_pch.hpp"

#include <optional>
#include <print>
#include <sstream>
#include <vector>

import fs8.cli;
import fs8.devices.queries;

using namespace fs8;

TEST(CLI, HelpFlagDetected) {
    static constexpr auto args   = arguments;
    char const* const     argv[] = {"prog", "--help"};
    auto const            parsed = args(2, argv);
    EXPECT_TRUE(parsed.help());
    EXPECT_TRUE(parsed.empty());
}

TEST(CLI, ShortHelpFlagDetected) {
    static constexpr auto args   = arguments;
    char const* const     argv[] = {"prog", "-h"};
    auto const            parsed = args(2, argv);
    EXPECT_TRUE(parsed.help());
    EXPECT_TRUE(parsed.empty());
}

TEST(CLI, PositionalsKept) {
    static constexpr auto args   = arguments;
    char const* const     argv[] = {"prog", "pen", "keyboard"};
    auto const            parsed = args(3, argv);
    EXPECT_FALSE(parsed.help());
    ASSERT_EQ(parsed.size(), 2);
    EXPECT_EQ(std::string_view{parsed.storage[0]}, "pen");
    EXPECT_EQ(std::string_view{parsed.storage[1]}, "keyboard");
}

TEST(CLI, FlagFilteredOut) {
    static constexpr auto args   = arguments.add_flag(basic_flag{"--grab", "-g", "Grab the input."});
    char const* const     argv[] = {"prog", "pen", "--grab", "keyboard"};
    auto const            parsed = args(4, argv);
    ASSERT_EQ(parsed.size(), 2);
    EXPECT_TRUE(parsed.has_flag("--grab"));
    EXPECT_TRUE(parsed.has_flag("-g"));
    EXPECT_EQ(std::string_view{parsed.storage[0]}, "pen");
    EXPECT_EQ(std::string_view{parsed.storage[1]}, "keyboard");
}

TEST(CLI, ValueFlagConsumesNext) {
    static constexpr auto args   = arguments.add_flag(basic_flag{"--device", "", "Device query.", true});
    char const* const     argv[] = {"prog", "--device", "/dev/input/event3", "pen"};
    auto const            parsed = args(4, argv);
    ASSERT_EQ(parsed.size(), 1);
    EXPECT_EQ(std::string_view{parsed.storage[0]}, "pen");
    EXPECT_TRUE(parsed.has_flag("--device"));
    auto const value = parsed.flag_value("--device");
    ASSERT_TRUE(value.has_value());
    EXPECT_EQ(*value, "/dev/input/event3");
}

TEST(CLI, DefaultsUsedWhenNoArgs) {
    static constexpr auto args   = arguments["pen", "keyboard"];
    char const* const     argv[] = {"prog"};
    auto const            parsed = args(1, argv);
    ASSERT_EQ(parsed.size(), 2);
    EXPECT_EQ(std::string_view{parsed.storage[0]}, "pen");
    EXPECT_EQ(std::string_view{parsed.storage[1]}, "keyboard");
    EXPECT_FALSE(parsed.help());
}

TEST(CLI, DefaultsUsedOnHelpPathOnlyWhenAsked) {
    static constexpr auto args   = arguments["pen", "keyboard"];
    char const* const     argv[] = {"prog", "--help"};
    auto const            parsed = args(2, argv);
    EXPECT_TRUE(parsed.help());
    EXPECT_TRUE(parsed.empty());
}

TEST(CLI, PipeThroughQueryTags) {
    static constexpr auto args   = arguments["pen"];
    char const* const     argv[] = {"prog", "/dev/input/event3"};
    auto const            parsed = args(2, argv);

    std::vector<owned_query> queries;
    for (auto const q : parsed | grab | required) {
        queries.push_back(q);
    }
    ASSERT_EQ(queries.size(), 1);
    EXPECT_TRUE(queries[0].grab);
    EXPECT_TRUE(queries[0].fail_on_no_match);
    EXPECT_FALSE(queries[0].value().fields.empty());
}

TEST(CLI, PrintCustomHelp) {
    static constexpr auto args   = arguments.positional("pen_device", "usb_keyboard_device").help(R"TEXT(Custom help text.)TEXT");
    char const* const     argv[] = {"prog", "--help"};
    auto const            parsed = args(2, argv);
    EXPECT_TRUE(parsed.help());

    testing::internal::CaptureStdout();
    parsed.print_help();
    EXPECT_EQ(testing::internal::GetCapturedStdout(), "Custom help text.\n");
}

TEST(CLI, AutoGeneratedHelpListsNamesAndFlags) {
    static constexpr auto args =
      arguments.positional("pen_device", "usb_keyboard_device").add_flag(basic_flag{"--grab", "-g", "Grab the input."});
    char const* const argv[] = {"prog", "--help"};
    auto const        parsed = args(2, argv);

    testing::internal::CaptureStdout();
    parsed.print_help();
    auto const out = testing::internal::GetCapturedStdout();
    EXPECT_NE(out.find("Usage: prog"), std::string::npos);
    EXPECT_NE(out.find("pen_device"), std::string::npos);
    EXPECT_NE(out.find("usb_keyboard_device"), std::string::npos);
    EXPECT_NE(out.find("-g | --grab"), std::string::npos);
    EXPECT_NE(out.find("-h | --help"), std::string::npos);
}
