#!/usr/bin/env python3
"""Generate modelf_data.cxx from category-based parameters.

Unlike the Model M tables (12 measured keys + interpolation), no Model F
recordings were analysed: every keycode is synthesised from its key-category
defaults plus a deterministic per-key jitter, mirroring the interpolation
helpers in gen-bucklespring.py.

Usage:
    python3 tools/gen-modelf.py
"""

from pathlib import Path

# ---------------------------------------------------------------------------
# Key categories (keycode ranges mirror get_category() in gen-bucklespring.py)
#
# Values describe an IBM Model F capacitive buckling spring: lighter and
# more metallic than the Model M — higher modes, longer ringing, a sharper
# snap, and less bottom-out thump.
# ---------------------------------------------------------------------------

CATEGORIES = {
    #                  res1_f  res1_q  res2_f  res2_q  ring   peak   contact snap   snap_bw
    "alpha":        (2100.0,  8.0,    950.0,  6.0,    6.5,  -3.0,   0.10,  1.60,  0.9),
    "number":       (1950.0,  8.0,    800.0,  5.0,    7.0,  -2.5,   0.15,  2.00,  1.0),
    "modifier":     (2350.0,  10.0,   1150.0, 7.0,    6.0,  -3.5,   0.08,  1.30,  0.8),
    "function":     (2900.0,  12.0,   2100.0, 12.0,   5.0,  -2.0,   0.15,  1.50,  0.8),
    "punctuation":  (2000.0,  8.0,    1050.0, 6.0,    6.0,  -2.8,   0.08,  1.40,  0.9),
    "numpad":       (2200.0,  8.0,    900.0,  5.0,    5.5,  -4.0,   0.12,  1.60,  0.9),
}

DEFAULT_CATEGORY = "alpha"


def get_category(keycode: int) -> str:
    if 0x02 <= keycode <= 0x0B:
        return "number"
    if 0x0C <= keycode <= 0x0D:
        return "punctuation"
    if keycode in (0x0E, 0x0F):
        return "modifier"
    if 0x10 <= keycode <= 0x19:
        return "alpha"
    if 0x1A <= keycode <= 0x1B:
        return "punctuation"
    if keycode in (0x1C, 0x1D):
        return "modifier"
    if 0x1E <= keycode <= 0x26:
        return "alpha"
    if 0x27 <= keycode <= 0x29:
        return "punctuation"
    if keycode in (0x2A, 0x36):
        return "modifier"
    if keycode == 0x2B:
        return "punctuation"
    if 0x2C <= keycode <= 0x32:
        return "alpha"
    if 0x33 <= keycode <= 0x35:
        return "punctuation"
    if keycode in (0x37, 0x38, 0x3A, 0x45, 0x46):
        return "modifier"
    if keycode == 0x39:
        return "modifier"  # space bar: big spring, low thump
    if 0x3B <= keycode <= 0x44:
        return "function"
    if 0x47 <= keycode <= 0x52:
        return "numpad"
    if 0x53 <= keycode <= 0x57:
        return "modifier"
    if 0x60 <= keycode <= 0x7D:
        return "function"
    return DEFAULT_CATEGORY


def jitter(keycode: int) -> float:
    """Deterministic per-key value in [0, 1) (same FNV-ish hash as gen-bucklespring)."""
    return ((keycode * 2654435761) & 0xFFFF) / 65535.0


def press_params(keycode: int) -> tuple[float, ...]:
    res1_f, res1_q, res2_f, res2_q, ring, peak, contact, snap, snap_bw = CATEGORIES[get_category(keycode)]
    v = jitter(keycode)
    spread = 1.0 + (v - 0.5) * 0.06  # modes vary +-3% per key
    return (
        res1_f * spread,
        res1_q,
        res2_f * spread,
        res2_q,
        ring * (1.0 + (v - 0.5) * 0.25),
        peak + (v - 0.5) * 1.5,
        contact,
        snap * (1.0 + (v - 0.5) * 0.4),
        snap_bw,
    )


def release_params(keycode: int) -> tuple[float, ...]:
    """Upstroke: same modes, shorter ring, quieter, snappier than the press."""
    p = list(press_params(keycode))
    p[4] *= 0.65  # ring_ms
    p[5] -= 1.5   # peak_dbfs
    p[7] *= 0.55  # snap_ms
    p[8] *= 0.85  # snap_bw_ms
    return tuple(p)


def generate_rows(params_fn) -> list[str]:
    lines = []
    for kc in range(256):
        p = params_fn(kc)
        lines.append(
            "        { "
            f"{p[0]:.1f}f, {p[1]:.1f}f, {p[2]:.1f}f, {p[3]:.1f}f, "
            f"{p[4]:.1f}f, {p[5]:.1f}f, {p[6]:.3f}f, {p[7]:.3f}f, {p[8]:.1f}f"
            + f" }},  // 0x{kc:02x}"
        )
    return lines


def generate_cxx() -> str:
    lines = [
        "// Auto-generated by tools/gen-modelf.py -- DO NOT EDIT.",
        "// Defines the Model F parameter arrays (declared extern in modelf_data.ixx).",
        "",
        "module;",
        "#include <array>",
        "",
        "module fs8.sound;",
        "",
        "import :bucklespring_data;",
        "import :modelf_data;",
        "",
        "using fs8::click_params;",
        "",
        "// clang-format off",
        "",
        "const std::array<click_params, 256> fs8::modelf_press_params = {{",
    ]
    lines += generate_rows(press_params)
    lines += ["}};", "", "const std::array<click_params, 256> fs8::modelf_release_params = {{"]
    lines += generate_rows(release_params)
    lines += ["}};", "", "// clang-format on", ""]
    return "\n".join(lines)


def main() -> None:
    out = Path(__file__).resolve().parent.parent / "sound" / "modelf_data.cxx"
    out.write_text(generate_cxx())
    print(f"Generated {out}")
    print("  256 press + 256 release parameter sets (category-based, no measured keys)")


if __name__ == "__main__":
    main()
