#!/usr/bin/env python3
"""Extract short attack samples from WAVs and emit C++ data.

Reads mono 16-bit 44100 Hz WAVs, cuts the first N ms (the transient),
normalizes, and writes:
  - sound/bucklespring_attack.ixx  (module partition: struct + extern decls)
  - sound/bucklespring_attack.cxx  (module impl: PCM blob + offset table)

Usage:
    python3 tools/gen-bucklespring-attack.py --wav-dir /path/to/wav
    python3 tools/gen-bucklespring-attack.py --wav-dir /path/to/wav --attack-ms 12
"""

import argparse
import struct
import sys
import wave
from pathlib import Path

# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------

DEFAULT_ATTACK_MS_PRESS = 12.0
DEFAULT_ATTACK_MS_RELEASE = 8.0
SAMPLE_RATE = 44100
PEAK_NORM = 0.95  # peak-normalize attack to this level

# Fallback keycode for missing WAVs: use nearest measured key
MEASURED_KEYS = [0x01, 0x02, 0x0e, 0x0f, 0x1c, 0x1e, 0x2a, 0x2c, 0x33, 0x34, 0x39, 0x3b]


def find_nearest_measured(keycode: int) -> int:
    return min(MEASURED_KEYS, key=lambda k: abs(k - keycode))


def read_wav_mono_f32(path: Path) -> tuple[list[float], int]:
    """Read a WAV file and return mono float32 samples + sample rate."""
    with wave.open(str(path), "rb") as wf:
        sr = wf.getframerate()
        nch = wf.getnchannels()
        sw = wf.getsampwidth()
        raw = wf.readframes(wf.getnframes())

    if sw == 2:
        samples = [s / 32768.0 for s in struct.unpack(f"<{len(raw) // 2}h", raw)]
    elif sw == 1:
        samples = [(s / 128.0) - 1.0 for s in raw]
    else:
        raise ValueError(f"Unsupported sample width: {sw}")

    if nch > 1:
        samples = samples[::nch]

    return samples, sr


def cut_attack(samples: list[float], sr: int, attack_ms: float) -> list[float]:
    """Cut the first attack_ms milliseconds and peak-normalize."""
    n = int(sr * attack_ms / 1000.0)
    n = min(n, len(samples))
    attack = samples[:n]

    # Peak-normalize
    peak = max(abs(s) for s in attack) if attack else 1.0
    if peak > 1e-9:
        scale = PEAK_NORM / peak
        attack = [s * scale for s in attack]

    return attack


def float_to_int16(data: list[float]) -> bytes:
    """Convert float samples in [-1, 1] to int16 PCM bytes."""
    return struct.pack(f"<{len(data)}h", *(max(-32768, min(32767, int(s * 32767.0))) for s in data))


def generate_attack_data(wav_dir: Path, attack_ms_press: float, attack_ms_release: float):
    """Read WAVs and build the attack table. Returns (blob_bytes, table)."""
    blob_parts: list[bytes] = []
    table: list[tuple[int, int]] = []  # (offset, frames) per (keycode, pressed)
    offset = 0

    for kc in range(256):
        for pressed in (True, False):
            suffix = "1" if pressed else "0"
            attack_ms = attack_ms_press if pressed else attack_ms_release

            wav_path = wav_dir / f"{kc:02x}-{suffix}.wav"
            if not wav_path.exists():
                # Fallback: try nearest measured key
                nearest = find_nearest_measured(kc)
                wav_path = wav_dir / f"{nearest:02x}-{suffix}.wav"

            if wav_path.exists():
                samples, sr = read_wav_mono_f32(wav_path)
                attack = cut_attack(samples, sr, attack_ms)
            else:
                # Ultimate fallback: silence (shouldn't happen with 209 WAVs)
                attack = [0.0] * int(SAMPLE_RATE * attack_ms / 1000.0)

            pcm = float_to_int16(attack)
            frames = len(attack)
            blob_parts.append(pcm)
            table.append((offset, frames))
            offset += len(pcm)

    blob = b"".join(blob_parts)
    return blob, table


def generate_ixx() -> str:
    return """\
// Auto-generated by tools/gen-bucklespring-attack.py -- DO NOT EDIT.
//
// Short attack samples cut from reference WAV recordings.
// Each entry holds a slice of the first few milliseconds of the real
// recording — the complex multi-burst transient that is hard to synthesize.
// The synthetic tail (in bucklespring.cxx) crossfades in after this window.

module;
#include <array>
#include <cstdint>
#include <span>

export module fs8.mods:bucklespring_attack;

export namespace fs8 {

    /// Offset + length into the attack PCM blob for one (keycode, pressed) pair.
    struct [[nodiscard]] attack_entry {
        uint32_t offset;  ///< byte offset into bucklespring_attack_blob
        uint16_t frames;  ///< number of mono int16 samples
    };

    /// Concatenated int16 PCM attack samples (mono, 44100 Hz, peak-normalized).
    extern const uint8_t bucklespring_attack_blob[];
    extern const uint32_t bucklespring_attack_blob_size;

    /// Lookup table: [keycode][pressed] -> attack_entry.
    /// Missing keys fall back to a nearby measured key's attack.
    extern const std::array<std::array<attack_entry, 2>, 256> bucklespring_attack_table;

    /// Attack sample rate (always 44100; resampled at render time).
    inline constexpr uint32_t attack_sample_rate = 44100;

} // namespace fs8
"""


def generate_cxx(blob: bytes, table: list[tuple[int, int]]) -> str:
    lines = []
    lines.append("// Auto-generated by tools/gen-bucklespring-attack.py -- DO NOT EDIT.")
    lines.append("// Attack samples from reference WAVs.")
    lines.append("//")
    lines.append("// To regenerate:")
    lines.append("//   python3 tools/gen-bucklespring-attack.py --wav-dir /path/to/wav")
    lines.append("")
    lines.append("module;")
    lines.append("#include <array>")
    lines.append("#include <cstdint>")
    lines.append("")
    lines.append("module fs8.mods;")
    lines.append("")
    lines.append("import :bucklespring_attack;")
    lines.append("")
    lines.append("using fs8::attack_entry;")
    lines.append("")
    lines.append("// clang-format off")
    lines.append("")

    # Blob
    lines.append(f"const uint8_t fs8::bucklespring_attack_blob[] = {{")
    # Write as hex, 16 bytes per line
    for i in range(0, len(blob), 16):
        chunk = blob[i : i + 16]
        hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"    {hex_vals},")
    lines.append(f"}};")
    lines.append(f"const uint32_t fs8::bucklespring_attack_blob_size = {len(blob)};")
    lines.append("")

    # Table
    lines.append("const std::array<std::array<attack_entry, 2>, 256> fs8::bucklespring_attack_table = {{")
    for kc in range(256):
        idx = kc * 2
        off_p, frames_p = table[idx]
        off_r, frames_r = table[idx + 1]
        lines.append(
            f"    {{{{ {{ {off_p}u, {frames_p} }}, {{ {off_r}u, {frames_r} }} }}}},"
            f"  // 0x{kc:02x}"
        )
    lines.append("}};")
    lines.append("")
    lines.append("// clang-format on")
    lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Extract attack samples from bucklespring WAVs")
    parser.add_argument("--wav-dir", type=str, required=True, help="Directory containing XX-Y.wav files")
    parser.add_argument("--attack-ms-press", type=float, default=DEFAULT_ATTACK_MS_PRESS, help="Attack window for press events (ms)")
    parser.add_argument("--attack-ms-release", type=float, default=DEFAULT_ATTACK_MS_RELEASE, help="Attack window for release events (ms)")
    args = parser.parse_args()

    wav_dir = Path(args.wav_dir)
    if not wav_dir.is_dir():
        print(f"Error: WAV directory not found: {wav_dir}", file=sys.stderr)
        sys.exit(1)

    sound_dir = Path(__file__).resolve().parent.parent / "sound"

    print(f"Reading WAVs from {wav_dir}")
    print(f"  Press attack:  {args.attack_ms_press:.1f} ms")
    print(f"  Release attack: {args.attack_ms_release:.1f} ms")

    blob, table = generate_attack_data(wav_dir, args.attack_ms_press, args.attack_ms_release)

    blob_frames = sum(f for _, f in table)
    print(f"  Blob: {len(blob)} bytes ({blob_frames} total samples)")
    print(f"  Table: {len(table)} entries (256 keys x 2 states)")

    # Write .ixx
    ixx_path = sound_dir / "bucklespring_attack.ixx"
    ixx_path.write_text(generate_ixx())
    print(f"Generated {ixx_path}")

    # Write .cxx
    cxx_path = sound_dir / "bucklespring_attack.cxx"
    cxx_path.write_text(generate_cxx(blob, table))
    print(f"Generated {cxx_path}")


if __name__ == "__main__":
    main()
