var annotated_dup =
[
    [ "details", "namespacedetails.html", [
      [ "prepend", "structdetails_1_1prepend.html", null ],
      [ "prepend< TupleT< L... >, F >", "structdetails_1_1prepend_3_01TupleT_3_01L_8_8_8_01_4_00_01F_01_4.html", "structdetails_1_1prepend_3_01TupleT_3_01L_8_8_8_01_4_00_01F_01_4" ],
      [ "unique_types", "structdetails_1_1unique__types.html", null ],
      [ "unique_types< TupleT< First, U... > >", "structdetails_1_1unique__types_3_01TupleT_3_01First_00_01U_8_8_8_01_4_01_4.html", "structdetails_1_1unique__types_3_01TupleT_3_01First_00_01U_8_8_8_01_4_01_4" ],
      [ "unique_types< TupleT<> >", "structdetails_1_1unique__types_3_01TupleT_3_4_01_4.html", "structdetails_1_1unique__types_3_01TupleT_3_4_01_4" ]
    ] ],
    [ "fs8", "namespacefs8.html", [
      [ "detail", "namespacefs8_1_1detail.html", [
        [ "modes_caller_info", "structfs8_1_1detail_1_1modes__caller__info.html", "structfs8_1_1detail_1_1modes__caller__info" ],
        [ "router_state", "structfs8_1_1detail_1_1router__state.html", "structfs8_1_1detail_1_1router__state" ]
      ] ],
      [ "idle_repeat", "namespacefs8_1_1idle__repeat.html", [
        [ "consistent", "structfs8_1_1idle__repeat_1_1consistent.html", "structfs8_1_1idle__repeat_1_1consistent" ],
        [ "exponential", "structfs8_1_1idle__repeat_1_1exponential.html", "structfs8_1_1idle__repeat_1_1exponential" ],
        [ "once", "structfs8_1_1idle__repeat_1_1once.html", "structfs8_1_1idle__repeat_1_1once" ]
      ] ],
      [ "xkb", "namespacefs8_1_1xkb.html", [
        [ "basic_state", "structfs8_1_1xkb_1_1basic__state.html", "structfs8_1_1xkb_1_1basic__state" ],
        [ "context", "structfs8_1_1xkb_1_1context.html", "structfs8_1_1xkb_1_1context" ],
        [ "handle_modifiers_type", "structfs8_1_1xkb_1_1handle__modifiers__type.html", null ],
        [ "key_position", "structfs8_1_1xkb_1_1key__position.html", "structfs8_1_1xkb_1_1key__position" ],
        [ "keymap", "structfs8_1_1xkb_1_1keymap.html", "structfs8_1_1xkb_1_1keymap" ],
        [ "xkb_error", "structfs8_1_1xkb_1_1xkb__error.html", "structfs8_1_1xkb_1_1xkb__error" ]
      ] ],
      [ "aho_state", "structfs8_1_1aho__state.html", "structfs8_1_1aho__state" ],
      [ "allow_multiple_matches_tag", "structfs8_1_1allow__multiple__matches__tag.html", "structfs8_1_1allow__multiple__matches__tag" ],
      [ "and_op", "structfs8_1_1and__op.html", "structfs8_1_1and__op" ],
      [ "any_dynamic_context", "structfs8_1_1any__dynamic__context.html", "structfs8_1_1any__dynamic__context" ],
      [ "any_dynamic_context_model", "structfs8_1_1any__dynamic__context__model.html", "structfs8_1_1any__dynamic__context__model" ],
      [ "app_template", "structfs8_1_1app__template.html", "structfs8_1_1app__template" ],
      [ "bash_runner", "structfs8_1_1bash__runner.html", "structfs8_1_1bash__runner" ],
      [ "basic_abs2rel", "structfs8_1_1basic__abs2rel.html", "structfs8_1_1basic__abs2rel" ],
      [ "basic_always_disable", "structfs8_1_1basic__always__disable.html", "structfs8_1_1basic__always__disable" ],
      [ "basic_always_enable", "structfs8_1_1basic__always__enable.html", "structfs8_1_1basic__always__enable" ],
      [ "basic_arguments", "structfs8_1_1basic__arguments.html", "structfs8_1_1basic__arguments" ],
      [ "basic_auto_mode_tag", "structfs8_1_1basic__auto__mode__tag.html", "structfs8_1_1basic__auto__mode__tag" ],
      [ "basic_autocomplete", "structfs8_1_1basic__autocomplete.html", "structfs8_1_1basic__autocomplete" ],
      [ "basic_benchmark", "structfs8_1_1basic__benchmark.html", "structfs8_1_1basic__benchmark" ],
      [ "basic_benchmark_all", "structfs8_1_1basic__benchmark__all.html", "structfs8_1_1basic__benchmark__all" ],
      [ "basic_benchmark_counter", "structfs8_1_1basic__benchmark__counter.html", "structfs8_1_1basic__benchmark__counter" ],
      [ "basic_benchmark_result", "structfs8_1_1basic__benchmark__result.html", "structfs8_1_1basic__benchmark__result" ],
      [ "basic_code_adaptor", "structfs8_1_1basic__code__adaptor.html", "structfs8_1_1basic__code__adaptor" ],
      [ "basic_context", "structfs8_1_1basic__context.html", "structfs8_1_1basic__context" ],
      [ "basic_debounce", "structfs8_1_1basic__debounce.html", "structfs8_1_1basic__debounce" ],
      [ "basic_device_id_of", "structfs8_1_1basic__device__id__of.html", "structfs8_1_1basic__device__id__of" ],
      [ "basic_device_is", "structfs8_1_1basic__device__is.html", "structfs8_1_1basic__device__is" ],
      [ "basic_device_query", "structfs8_1_1basic__device__query.html", "structfs8_1_1basic__device__query" ],
      [ "basic_drop", "structfs8_1_1basic__drop.html", "structfs8_1_1basic__drop" ],
      [ "basic_drop_abs", "structfs8_1_1basic__drop__abs.html", "structfs8_1_1basic__drop__abs" ],
      [ "basic_drop_adjacent_repeats", "structfs8_1_1basic__drop__adjacent__repeats.html", "structfs8_1_1basic__drop__adjacent__repeats" ],
      [ "basic_drop_big_jumps", "structfs8_1_1basic__drop__big__jumps.html", "structfs8_1_1basic__drop__big__jumps" ],
      [ "basic_drop_caps", "structfs8_1_1basic__drop__caps.html", "structfs8_1_1basic__drop__caps" ],
      [ "basic_drop_device", "structfs8_1_1basic__drop__device.html", "structfs8_1_1basic__drop__device" ],
      [ "basic_drop_emitted", "structfs8_1_1basic__drop__emitted.html", "structfs8_1_1basic__drop__emitted" ],
      [ "basic_drop_event", "structfs8_1_1basic__drop__event.html", "structfs8_1_1basic__drop__event" ],
      [ "basic_drop_fast_repeats", "structfs8_1_1basic__drop__fast__repeats.html", "structfs8_1_1basic__drop__fast__repeats" ],
      [ "basic_drop_init_moves", "structfs8_1_1basic__drop__init__moves.html", "structfs8_1_1basic__drop__init__moves" ],
      [ "basic_drop_keys", "structfs8_1_1basic__drop__keys.html", "structfs8_1_1basic__drop__keys" ],
      [ "basic_drop_late_syn", "structfs8_1_1basic__drop__late__syn.html", "structfs8_1_1basic__drop__late__syn" ],
      [ "basic_drop_missing_syns", "structfs8_1_1basic__drop__missing__syns.html", "structfs8_1_1basic__drop__missing__syns" ],
      [ "basic_drop_mouse_clicks", "structfs8_1_1basic__drop__mouse__clicks.html", "structfs8_1_1basic__drop__mouse__clicks" ],
      [ "basic_drop_mouse_moves", "structfs8_1_1basic__drop__mouse__moves.html", "structfs8_1_1basic__drop__mouse__moves" ],
      [ "basic_drop_msc_scan", "structfs8_1_1basic__drop__msc__scan.html", "structfs8_1_1basic__drop__msc__scan" ],
      [ "basic_drop_origin", "structfs8_1_1basic__drop__origin.html", "structfs8_1_1basic__drop__origin" ],
      [ "basic_drop_orphan_abs", "structfs8_1_1basic__drop__orphan__abs.html", "structfs8_1_1basic__drop__orphan__abs" ],
      [ "basic_drop_owned", "structfs8_1_1basic__drop__owned.html", "structfs8_1_1basic__drop__owned" ],
      [ "basic_drop_pen_out_of_bounds", "structfs8_1_1basic__drop__pen__out__of__bounds.html", "structfs8_1_1basic__drop__pen__out__of__bounds" ],
      [ "basic_drop_repeats_of", "structfs8_1_1basic__drop__repeats__of.html", "structfs8_1_1basic__drop__repeats__of" ],
      [ "basic_drop_self", "structfs8_1_1basic__drop__self.html", "structfs8_1_1basic__drop__self" ],
      [ "basic_drop_start_moves", "structfs8_1_1basic__drop__start__moves.html", "structfs8_1_1basic__drop__start__moves" ],
      [ "basic_drop_tablet", "structfs8_1_1basic__drop__tablet.html", "structfs8_1_1basic__drop__tablet" ],
      [ "basic_drop_zero_mouse_moves", "structfs8_1_1basic__drop__zero__mouse__moves.html", "structfs8_1_1basic__drop__zero__mouse__moves" ],
      [ "basic_dynamic_context", "structfs8_1_1basic__dynamic__context.html", "structfs8_1_1basic__dynamic__context" ],
      [ "basic_dynamic_context_view", "structfs8_1_1basic__dynamic__context__view.html", "structfs8_1_1basic__dynamic__context__view" ],
      [ "basic_emit", "structfs8_1_1basic__emit.html", "structfs8_1_1basic__emit" ],
      [ "basic_emit_all", "structfs8_1_1basic__emit__all.html", "structfs8_1_1basic__emit__all" ],
      [ "basic_enforce_key_state", "structfs8_1_1basic__enforce__key__state.html", "structfs8_1_1basic__enforce__key__state" ],
      [ "basic_evtest_output", "structfs8_1_1basic__evtest__output.html", "structfs8_1_1basic__evtest__output" ],
      [ "basic_exit_pipeline", "structfs8_1_1basic__exit__pipeline.html", "structfs8_1_1basic__exit__pipeline" ],
      [ "basic_find_devices", "structfs8_1_1basic__find__devices.html", "structfs8_1_1basic__find__devices" ],
      [ "basic_flag", "structfs8_1_1basic__flag.html", "structfs8_1_1basic__flag" ],
      [ "basic_from_chained", "structfs8_1_1basic__from__chained.html", "structfs8_1_1basic__from__chained" ],
      [ "basic_from_device", "structfs8_1_1basic__from__device.html", "structfs8_1_1basic__from__device" ],
      [ "basic_from_evtest", "structfs8_1_1basic__from__evtest.html", "structfs8_1_1basic__from__evtest" ],
      [ "basic_from_input", "structfs8_1_1basic__from__input.html", "structfs8_1_1basic__from__input" ],
      [ "basic_from_live_view", "structfs8_1_1basic__from__live__view.html", "structfs8_1_1basic__from__live__view" ],
      [ "basic_from_stdin", "structfs8_1_1basic__from__stdin.html", "structfs8_1_1basic__from__stdin" ],
      [ "basic_group_mod", "structfs8_1_1basic__group__mod.html", "structfs8_1_1basic__group__mod" ],
      [ "basic_held", "structfs8_1_1basic__held.html", "structfs8_1_1basic__held" ],
      [ "basic_held_gate", "structfs8_1_1basic__held__gate.html", "structfs8_1_1basic__held__gate" ],
      [ "basic_idle_detector", "structfs8_1_1basic__idle__detector.html", "structfs8_1_1basic__idle__detector" ],
      [ "basic_input_manager", "structfs8_1_1basic__input__manager.html", "structfs8_1_1basic__input__manager" ],
      [ "basic_interceptor", "structfs8_1_1basic__interceptor.html", "structfs8_1_1basic__interceptor" ],
      [ "basic_io_manager", "structfs8_1_1basic__io__manager.html", "structfs8_1_1basic__io__manager" ],
      [ "basic_kalman_filter", "structfs8_1_1basic__kalman__filter.html", "structfs8_1_1basic__kalman__filter" ],
      [ "basic_key", "structfs8_1_1basic__key.html", "structfs8_1_1basic__key" ],
      [ "basic_keydown", "structfs8_1_1basic__keydown.html", "structfs8_1_1basic__keydown" ],
      [ "basic_keys_state", "structfs8_1_1basic__keys__state.html", "structfs8_1_1basic__keys__state" ],
      [ "basic_keyup", "structfs8_1_1basic__keyup.html", "structfs8_1_1basic__keyup" ],
      [ "basic_led_off", "structfs8_1_1basic__led__off.html", "structfs8_1_1basic__led__off" ],
      [ "basic_led_on", "structfs8_1_1basic__led__on.html", "structfs8_1_1basic__led__on" ],
      [ "basic_led_state", "structfs8_1_1basic__led__state.html", "structfs8_1_1basic__led__state" ],
      [ "basic_led_toggle", "structfs8_1_1basic__led__toggle.html", "structfs8_1_1basic__led__toggle" ],
      [ "basic_lerp", "structfs8_1_1basic__lerp.html", "structfs8_1_1basic__lerp" ],
      [ "basic_limit_mouse_travel", "structfs8_1_1basic__limit__mouse__travel.html", "structfs8_1_1basic__limit__mouse__travel" ],
      [ "basic_live_view_output", "structfs8_1_1basic__live__view__output.html", "structfs8_1_1basic__live__view__output" ],
      [ "basic_log", "structfs8_1_1basic__log.html", "structfs8_1_1basic__log" ],
      [ "basic_log_and_drop", "structfs8_1_1basic__log__and__drop.html", "structfs8_1_1basic__log__and__drop" ],
      [ "basic_log_diagnostics", "structfs8_1_1basic__log__diagnostics.html", "structfs8_1_1basic__log__diagnostics" ],
      [ "basic_longtime_released", "structfs8_1_1basic__longtime__released.html", "structfs8_1_1basic__longtime__released" ],
      [ "basic_low_pass_filter", "structfs8_1_1basic__low__pass__filter.html", "structfs8_1_1basic__low__pass__filter" ],
      [ "basic_mice_quantifier", "structfs8_1_1basic__mice__quantifier.html", "structfs8_1_1basic__mice__quantifier" ],
      [ "basic_mod_updater", "structfs8_1_1basic__mod__updater.html", "structfs8_1_1basic__mod__updater" ],
      [ "basic_modes", "structfs8_1_1basic__modes.html", "structfs8_1_1basic__modes" ],
      [ "basic_momentum_base", "structfs8_1_1basic__momentum__base.html", "structfs8_1_1basic__momentum__base" ],
      [ "basic_momentum_scroll", "structfs8_1_1basic__momentum__scroll.html", "structfs8_1_1basic__momentum__scroll" ],
      [ "basic_mouse_history", "structfs8_1_1basic__mouse__history.html", "structfs8_1_1basic__mouse__history" ],
      [ "basic_mouse_to_scroll", "structfs8_1_1basic__mouse__to__scroll.html", "structfs8_1_1basic__mouse__to__scroll" ],
      [ "basic_multi_click", "structfs8_1_1basic__multi__click.html", "structfs8_1_1basic__multi__click" ],
      [ "basic_noop", "structfs8_1_1basic__noop.html", "structfs8_1_1basic__noop" ],
      [ "basic_on", "structfs8_1_1basic__on.html", "structfs8_1_1basic__on" ],
      [ "basic_on_fail", "structfs8_1_1basic__on__fail.html", "structfs8_1_1basic__on__fail" ],
      [ "basic_on_held", "structfs8_1_1basic__on__held.html", "structfs8_1_1basic__on__held" ],
      [ "basic_once", "structfs8_1_1basic__once.html", "structfs8_1_1basic__once" ],
      [ "basic_only_device", "structfs8_1_1basic__only__device.html", "structfs8_1_1basic__only__device" ],
      [ "basic_only_ok", "structfs8_1_1basic__only__ok.html", "structfs8_1_1basic__only__ok" ],
      [ "basic_output_selector", "structfs8_1_1basic__output__selector.html", "structfs8_1_1basic__output__selector" ],
      [ "basic_parsed_args", "structfs8_1_1basic__parsed__args.html", "structfs8_1_1basic__parsed__args" ],
      [ "basic_pass_trigger_tag", "structfs8_1_1basic__pass__trigger__tag.html", "structfs8_1_1basic__pass__trigger__tag" ],
      [ "basic_pen2mice", "structfs8_1_1basic__pen2mice.html", "structfs8_1_1basic__pen2mice" ],
      [ "basic_pen2touch", "structfs8_1_1basic__pen2touch.html", "structfs8_1_1basic__pen2touch" ],
      [ "basic_pressed", "structfs8_1_1basic__pressed.html", "structfs8_1_1basic__pressed" ],
      [ "basic_pressed_any", "structfs8_1_1basic__pressed__any.html", "structfs8_1_1basic__pressed__any" ],
      [ "basic_pressure2mouse_clicks", "structfs8_1_1basic__pressure2mouse__clicks.html", "structfs8_1_1basic__pressure2mouse__clicks" ],
      [ "basic_put", "structfs8_1_1basic__put.html", "structfs8_1_1basic__put" ],
      [ "basic_quantifier", "structfs8_1_1basic__quantifier.html", "structfs8_1_1basic__quantifier" ],
      [ "basic_record", "structfs8_1_1basic__record.html", "structfs8_1_1basic__record" ],
      [ "basic_replace", "structfs8_1_1basic__replace.html", "structfs8_1_1basic__replace" ],
      [ "basic_replace_code", "structfs8_1_1basic__replace__code.html", "structfs8_1_1basic__replace__code" ],
      [ "basic_router", "structfs8_1_1basic__router.html", "structfs8_1_1basic__router" ],
      [ "basic_scale_move", "structfs8_1_1basic__scale__move.html", "structfs8_1_1basic__scale__move" ],
      [ "basic_scale_pen", "structfs8_1_1basic__scale__pen.html", "structfs8_1_1basic__scale__pen" ],
      [ "basic_schedule_emit", "structfs8_1_1basic__schedule__emit.html", "structfs8_1_1basic__schedule__emit" ],
      [ "basic_scheduled_emitter", "structfs8_1_1basic__scheduled__emitter.html", "structfs8_1_1basic__scheduled__emitter" ],
      [ "basic_scheduler", "structfs8_1_1basic__scheduler.html", "structfs8_1_1basic__scheduler" ],
      [ "basic_search_engine", "structfs8_1_1basic__search__engine.html", "structfs8_1_1basic__search__engine" ],
      [ "basic_self_emitted", "structfs8_1_1basic__self__emitted.html", "structfs8_1_1basic__self__emitted" ],
      [ "basic_singleton", "structfs8_1_1basic__singleton.html", "structfs8_1_1basic__singleton" ],
      [ "basic_startup_key_releases", "structfs8_1_1basic__startup__key__releases.html", "structfs8_1_1basic__startup__key__releases" ],
      [ "basic_std_output", "structfs8_1_1basic__std__output.html", "structfs8_1_1basic__std__output" ],
      [ "basic_stopper", "structfs8_1_1basic__stopper.html", "structfs8_1_1basic__stopper" ],
      [ "basic_swipe", "structfs8_1_1basic__swipe.html", "structfs8_1_1basic__swipe" ],
      [ "basic_swipe_detector", "structfs8_1_1basic__swipe__detector.html", "structfs8_1_1basic__swipe__detector" ],
      [ "basic_switch_mode", "structfs8_1_1basic__switch__mode.html", "structfs8_1_1basic__switch__mode" ],
      [ "basic_timed_typed", "structfs8_1_1basic__timed__typed.html", "structfs8_1_1basic__timed__typed" ],
      [ "basic_to_evdev", "structfs8_1_1basic__to__evdev.html", "structfs8_1_1basic__to__evdev" ],
      [ "basic_to_queries", "structfs8_1_1basic__to__queries.html", "structfs8_1_1basic__to__queries" ],
      [ "basic_toggle_off", "structfs8_1_1basic__toggle__off.html", "structfs8_1_1basic__toggle__off" ],
      [ "basic_type_string", "structfs8_1_1basic__type__string.html", "structfs8_1_1basic__type__string" ],
      [ "basic_typed", "structfs8_1_1basic__typed.html", "structfs8_1_1basic__typed" ],
      [ "basic_uinput", "structfs8_1_1basic__uinput.html", "structfs8_1_1basic__uinput" ],
      [ "consteval_copyable", "structfs8_1_1consteval__copyable.html", "structfs8_1_1consteval__copyable" ],
      [ "construct_it_from", "structfs8_1_1construct__it__from.html", "structfs8_1_1construct__it__from" ],
      [ "context_with_impl", "structfs8_1_1context__with__impl.html", null ],
      [ "context_with_impl< CtxT, Mods... >", "structfs8_1_1context__with__impl_3_01CtxT_00_01Mods_8_8_8_01_4.html", "structfs8_1_1context__with__impl_3_01CtxT_00_01Mods_8_8_8_01_4" ],
      [ "context_with_impl<>", "structfs8_1_1context__with__impl_3_4.html", "structfs8_1_1context__with__impl_3_4" ],
      [ "default_evtest_format", "structfs8_1_1default__evtest__format.html", "structfs8_1_1default__evtest__format" ],
      [ "dev_cap", "structfs8_1_1dev__cap.html", "structfs8_1_1dev__cap" ],
      [ "dev_cap_view", "structfs8_1_1dev__cap__view.html", "structfs8_1_1dev__cap__view" ],
      [ "device_change_handle", "structfs8_1_1device__change__handle.html", "structfs8_1_1device__change__handle" ],
      [ "device_live_state", "structfs8_1_1device__live__state.html", "structfs8_1_1device__live__state" ],
      [ "dynamic_scope", "structfs8_1_1dynamic__scope.html", "structfs8_1_1dynamic__scope" ],
      [ "dynamic_scope< T, ConcreteT >", "structfs8_1_1dynamic__scope_3_01T_00_01ConcreteT_01_4.html", "structfs8_1_1dynamic__scope_3_01T_00_01ConcreteT_01_4" ],
      [ "evdev", "structfs8_1_1evdev.html", "structfs8_1_1evdev" ],
      [ "event_code", "structfs8_1_1event__code.html", "structfs8_1_1event__code" ],
      [ "event_type", "structfs8_1_1event__type.html", "structfs8_1_1event__type" ],
      [ "exe_hash_solution", "structfs8_1_1exe__hash__solution.html", "structfs8_1_1exe__hash__solution" ],
      [ "fail_on_no_match_tag", "structfs8_1_1fail__on__no__match__tag.html", "structfs8_1_1fail__on__no__match__tag" ],
      [ "fork_index_guard", "structfs8_1_1fork__index__guard.html", "structfs8_1_1fork__index__guard" ],
      [ "get_variables_tag", "structfs8_1_1get__variables__tag.html", "structfs8_1_1get__variables__tag" ],
      [ "global_binding", "structfs8_1_1global__binding.html", "structfs8_1_1global__binding" ],
      [ "grab_tag", "structfs8_1_1grab__tag.html", "structfs8_1_1grab__tag" ],
      [ "held_key", "structfs8_1_1held__key.html", "structfs8_1_1held__key" ],
      [ "high_threshold_tag", "structfs8_1_1high__threshold__tag.html", "structfs8_1_1high__threshold__tag" ],
      [ "index_at_impl", "structfs8_1_1index__at__impl.html", "structfs8_1_1index__at__impl" ],
      [ "index_at_impl< Index, F, F, Ts... >", "structfs8_1_1index__at__impl_3_01Index_00_01F_00_01F_00_01Ts_8_8_8_01_4.html", "structfs8_1_1index__at__impl_3_01Index_00_01F_00_01F_00_01Ts_8_8_8_01_4" ],
      [ "intercept_hash_solution", "structfs8_1_1intercept__hash__solution.html", "structfs8_1_1intercept__hash__solution" ],
      [ "io_fd", "structfs8_1_1io__fd.html", "structfs8_1_1io__fd" ],
      [ "is_range_adaptor_closure", "structfs8_1_1is__range__adaptor__closure.html", "structfs8_1_1is__range__adaptor__closure" ],
      [ "key_event", "structfs8_1_1key__event.html", "structfs8_1_1key__event" ],
      [ "keyboard_runner", "structfs8_1_1keyboard__runner.html", "structfs8_1_1keyboard__runner" ],
      [ "keynames_type", "structfs8_1_1keynames__type.html", "structfs8_1_1keynames__type" ],
      [ "live_view", "structfs8_1_1live__view.html", "structfs8_1_1live__view" ],
      [ "live_view_format", "structfs8_1_1live__view__format.html", "structfs8_1_1live__view__format" ],
      [ "live_view_parse_result", "structfs8_1_1live__view__parse__result.html", "structfs8_1_1live__view__parse__result" ],
      [ "low_threshold_tag", "structfs8_1_1low__threshold__tag.html", "structfs8_1_1low__threshold__tag" ],
      [ "matches_limit", "structfs8_1_1matches__limit.html", "structfs8_1_1matches__limit" ],
      [ "matches_percentage", "structfs8_1_1matches__percentage.html", "structfs8_1_1matches__percentage" ],
      [ "mod_of_t", "structfs8_1_1mod__of__t.html", "structfs8_1_1mod__of__t" ],
      [ "mod_of_t< ModConcept, Func, Funcs... >", "structfs8_1_1mod__of__t_3_01ModConcept_00_01Func_00_01Funcs_8_8_8_01_4.html", "structfs8_1_1mod__of__t_3_01ModConcept_00_01Func_00_01Funcs_8_8_8_01_4" ],
      [ "mod_of_t< TT< T... >, TT< U... >, Funcs... >", "structfs8_1_1mod__of__t_3_01TT_3_01T_8_8_8_01_4_00_01TT_3_01U_8_8_8_01_4_00_01Funcs_8_8_8_01_4.html", "structfs8_1_1mod__of__t_3_01TT_3_01T_8_8_8_01_4_00_01TT_3_01U_8_8_8_01_4_00_01Funcs_8_8_8_01_4" ],
      [ "momentum_calculator", "structfs8_1_1momentum__calculator.html", "structfs8_1_1momentum__calculator" ],
      [ "momentum_config", "structfs8_1_1momentum__config.html", "structfs8_1_1momentum__config" ],
      [ "mouse_accum", "structfs8_1_1mouse__accum.html", "structfs8_1_1mouse__accum" ],
      [ "named_solution", "structfs8_1_1named__solution.html", "structfs8_1_1named__solution" ],
      [ "nullable_indirect", "structfs8_1_1nullable__indirect.html", "structfs8_1_1nullable__indirect" ],
      [ "op_not", "structfs8_1_1op__not.html", "structfs8_1_1op__not" ],
      [ "operator_adaptor", "structfs8_1_1operator__adaptor.html", "structfs8_1_1operator__adaptor" ],
      [ "or_op", "structfs8_1_1or__op.html", "structfs8_1_1or__op" ],
      [ "owned_query", "structfs8_1_1owned__query.html", "structfs8_1_1owned__query" ],
      [ "parsed_evtest_event", "structfs8_1_1parsed__evtest__event.html", "structfs8_1_1parsed__evtest__event" ],
      [ "pimpl_idiom", "structfs8_1_1pimpl__idiom.html", "structfs8_1_1pimpl__idiom" ],
      [ "pipeline_hash_solution", "structfs8_1_1pipeline__hash__solution.html", "structfs8_1_1pipeline__hash__solution" ],
      [ "plain_pimpl_idiom", "structfs8_1_1plain__pimpl__idiom.html", "structfs8_1_1plain__pimpl__idiom" ],
      [ "query_provider_handle", "structfs8_1_1query__provider__handle.html", "structfs8_1_1query__provider__handle" ],
      [ "query_term", "structfs8_1_1query__term.html", "structfs8_1_1query__term" ],
      [ "route", "structfs8_1_1route.html", "structfs8_1_1route" ],
      [ "run", "structfs8_1_1run.html", "structfs8_1_1run" ],
      [ "special_event", "structfs8_1_1special__event.html", "structfs8_1_1special__event" ],
      [ "sub_pipeline_guard", "structfs8_1_1sub__pipeline__guard.html", "structfs8_1_1sub__pipeline__guard" ],
      [ "systemd_service", "structfs8_1_1systemd__service.html", "structfs8_1_1systemd__service" ],
      [ "template_file", "structfs8_1_1template__file.html", "structfs8_1_1template__file" ],
      [ "thread_binding", "structfs8_1_1thread__binding.html", "structfs8_1_1thread__binding" ],
      [ "type_at_impl", "structfs8_1_1type__at__impl.html", "structfs8_1_1type__at__impl" ],
      [ "type_at_impl< 0, T, Ts... >", "structfs8_1_1type__at__impl_3_010_00_01T_00_01Ts_8_8_8_01_4.html", "structfs8_1_1type__at__impl_3_010_00_01T_00_01Ts_8_8_8_01_4" ],
      [ "type_id_t", "structfs8_1_1type__id__t.html", null ],
      [ "udev", "structfs8_1_1udev.html", "structfs8_1_1udev" ],
      [ "udev_device", "structfs8_1_1udev__device.html", "structfs8_1_1udev__device" ],
      [ "udev_device_pick", "structfs8_1_1udev__device__pick.html", "structfs8_1_1udev__device__pick" ],
      [ "udev_enumerate", "structfs8_1_1udev__enumerate.html", "structfs8_1_1udev__enumerate" ],
      [ "udev_hwdb", "structfs8_1_1udev__hwdb.html", "structfs8_1_1udev__hwdb" ],
      [ "udev_list_entry", "structfs8_1_1udev__list__entry.html", "structfs8_1_1udev__list__entry" ],
      [ "udev_monitor", "structfs8_1_1udev__monitor.html", "structfs8_1_1udev__monitor" ],
      [ "udev_queue", "structfs8_1_1udev__queue.html", "structfs8_1_1udev__queue" ],
      [ "user_event", "structfs8_1_1user__event.html", "structfs8_1_1user__event" ],
      [ "user_events", "structfs8_1_1user__events.html", null ],
      [ "value_or_view", "structfs8_1_1value__or__view.html", "structfs8_1_1value__or__view" ],
      [ "value_or_view< T, std::dynamic_extent >", "structfs8_1_1value__or__view_3_01T_00_01std_1_1dynamic__extent_01_4.html", "structfs8_1_1value__or__view_3_01T_00_01std_1_1dynamic__extent_01_4" ],
      [ "var_type", "structfs8_1_1var__type.html", "structfs8_1_1var__type" ],
      [ "variable_pointer", "structfs8_1_1variable__pointer.html", "structfs8_1_1variable__pointer" ],
      [ "variable_size", "structfs8_1_1variable__size.html", "structfs8_1_1variable__size" ],
      [ "variable_size< ModT >", "structfs8_1_1variable__size_3_01ModT_01_4.html", "structfs8_1_1variable__size_3_01ModT_01_4" ],
      [ "variable_size<>", "structfs8_1_1variable__size_3_4.html", "structfs8_1_1variable__size_3_4" ],
      [ "variable_types", "structfs8_1_1variable__types.html", null ],
      [ "variable_types< Templ, T, ModT, ModsT... >", "structfs8_1_1variable__types_3_01Templ_00_01T_00_01ModT_00_01ModsT_8_8_8_01_4.html", null ],
      [ "variable_types< Templ, Templ< T... > >", "structfs8_1_1variable__types_3_01Templ_00_01Templ_3_01T_8_8_8_01_4_01_4.html", "structfs8_1_1variable__types_3_01Templ_00_01Templ_3_01T_8_8_8_01_4_01_4" ],
      [ "variable_types< Templ, Templ< T... >, ModT, ModsT... >", "structfs8_1_1variable__types_3_01Templ_00_01Templ_3_01T_8_8_8_01_4_00_01ModT_00_01ModsT_8_8_8_01_4.html", null ],
      [ "velocity_tracker", "structfs8_1_1velocity__tracker.html", "structfs8_1_1velocity__tracker" ],
      [ "visit_impl", "structfs8_1_1visit__impl.html", "structfs8_1_1visit__impl" ],
      [ "visit_impl< 0 >", "structfs8_1_1visit__impl_3_010_01_4.html", "structfs8_1_1visit__impl_3_010_01_4" ]
    ] ],
    [ "my_libevdev_uinput", "structmy__libevdev__uinput.html", "structmy__libevdev__uinput" ]
];