var modules_dup =
[
    [ "fs8.bash", "module_fs8_8bash.html", "module_fs8_8bash" ],
    [ "fs8.devices.capabilities", "module_fs8_8devices_8capabilities.html", "module_fs8_8devices_8capabilities" ],
    [ "fs8.devices.evdev", "module_fs8_8devices_8evdev.html", "module_fs8_8devices_8evdev" ],
    [ "fs8.devices.event_codes", "module_fs8_8devices_8event__codes.html", "module_fs8_8devices_8event__codes" ],
    [ "fs8.devices.key_codes", "module_fs8_8devices_8key__codes.html", "module_fs8_8devices_8key__codes" ],
    [ "fs8.devices.queries", "module_fs8_8devices_8queries.html", "module_fs8_8devices_8queries" ],
    [ "fs8.devices.udev", "module_fs8_8devices_8udev.html", "module_fs8_8devices_8udev" ],
    [ "fs8.lib.xkb.event2unicode", "module_fs8_8lib_8xkb_8event2unicode.html", "module_fs8_8lib_8xkb_8event2unicode" ],
    [ "fs8.lib.evtest", "module_fs8_8lib_8evtest.html", "module_fs8_8lib_8evtest" ],
    [ "fs8.lib.xkb.how2type", "module_fs8_8lib_8xkb_8how2type.html", "module_fs8_8lib_8xkb_8how2type" ],
    [ "fs8.lib.mod_parser", "module_fs8_8lib_8mod__parser.html", "module_fs8_8lib_8mod__parser" ],
    [ "fs8.lib.xkb", "module_fs8_8lib_8xkb.html", "module_fs8_8lib_8xkb" ],
    [ "fs8.cli", "module_fs8_8cli.html", "module_fs8_8cli" ],
    [ "fs8.context", "module_fs8_8context.html", "module_fs8_8context" ],
    [ "fs8.event", "module_fs8_8event.html", "module_fs8_8event" ],
    [ "fs8.keyboard", "module_fs8_8keyboard.html", "module_fs8_8keyboard" ],
    [ "fs8.log", "module_fs8_8log.html", "module_fs8_8log" ],
    [ "fs8", "module_fs8.html", null ],
    [ "fs8.scaffold", "module_fs8_8scaffold.html", "module_fs8_8scaffold" ],
    [ "fs8.systemd", "module_fs8_8systemd.html", "module_fs8_8systemd" ],
    [ "fs8.translate", "module_fs8_8translate.html", "module_fs8_8translate" ],
    [ "fs8.utils", "module_fs8_8utils.html", "module_fs8_8utils" ],
    [ "fs8.mods", "module_fs8_8mods.html", "module_fs8_8mods" ],
    [ "dynamic_scoping", "module_dynamic__scoping.html", "module_dynamic__scoping" ],
    [ "fs8.easings", "module_fs8_8easings.html", "module_fs8_8easings" ],
    [ "fs8.hash", "module_fs8_8hash.html", "module_fs8_8hash" ],
    [ "fs8.nullable_indirect", "module_fs8_8nullable__indirect.html", "module_fs8_8nullable__indirect" ],
    [ "fs8.parsing", "module_fs8_8parsing.html", "module_fs8_8parsing" ],
    [ "fs8.pimpl", "module_fs8_8pimpl.html", "module_fs8_8pimpl" ],
    [ "fs8.strings", "module_fs8_8strings.html", "module_fs8_8strings" ],
    [ "fs8.traits", "module_fs8_8traits.html", "module_fs8_8traits" ]
];